
FIND_PATH(LIBDVIDCPP_INCLUDE_DIR libdvid/DVIDNodeService.h)
FIND_LIBRARY(LIBDVIDCPP_LIBRARY NAMES dvidcpp)

message(STATUS "LIBDVIDCPP_INCLUDE_DIR: ${LIBDVIDCPP_INCLUDE_DIR}")
message(STATUS "LIBDVIDCPP_LIBRARY:     ${LIBDVIDCPP_LIBRARY}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBDVIDCPP DEFAULT_MSG LIBDVIDCPP_INCLUDE_DIR LIBDVIDCPP_LIBRARY)

if (LIBDVIDCPP_FOUND)
    message(STATUS "Found libdvid-cpp headers in ${LIBDVIDCPP_INCLUDE_DIR}")
    message(STATUS "Found libdvid-cpp library in ${LIBDVIDCPP_LIBRARY}")
    # Provide the plural-named variables, too,
    # for compatibility packages that also work with BuildEM.
    set(LIBDVIDCPP_INCLUDE_DIRS ${LIBDVIDCPP_INCLUDE_DIR})
    set(LIBDVIDCPP_LIBRARIES ${LIBDVIDCPP_LIBRARY})
else()
    message(FATAL_ERROR "Could not locate libdvid-cpp.  Try setting LIBDVIDCPP_INCLUDE_DIR and LIBDVIDCPP_LIBRARY.")
    set(LIBDVIDCPP_INCLUDE_DIR LIBDVIDCPP_INCLUDE_DIR-NOTFOUND)
    set(LIBDVIDCPP_LIBRARY LIBDVIDCPP_LIBRARY-NOTFOUND)
endif()
